name: examen-chuleta

on:
  push:
    branches:
      - nueva-caracteristica

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Bajar código
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies and run tests
      run: |
        pip install pytest
        pytest test.py

    #- name: Login to Docker Hub
    #  uses: docker/login-action@v3
    #  with:
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false  # No subir la imagen a ningún registro, según los requisitos
        # tags: Endikson/holamundo (nombre de la imagen

  #test:
   #runs-on: ubuntu-latest
   #needs: build (no se ejecutará hasta que acabe build)
   #steps:

  #Para ejecutar una tarea en distintos runners
  #test:
     #runs-on: ${{matrix.os}}
     #strategy:
       #matrix:
         #os: [ubuntu-latest, windows-latest, macOs-latest]
