name: Test de Python con Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Instalar dependencias
      run: |
        pip install pytest

    - name: Ejecutar pruebas
      run: |
        pytest test.py
